hackjutsu/Lepton

- app/containers/userPanel/index.js
This change will enable users to open their github page when they click on their profile picture in the app.
> update index file

- package.json
18.7.0 seems to introduce some unexpected breaking changes. I would like to lock its version to 18.3.5 as a workaround at this moment.
> Lock the electron-builder version

- .gitignore
- README.md
- app/utilities/githubApi/index.js
- configs/networkDummy.js
- package.json
Resolve issue #45 #58.
Proxy address should be filled in `config/network.js` copied from template `config/networkDummy.js`.
Of cause, the proxy server should be configured by yourself :)
Example:
```
module.exports = {
proxy: 'socks://localhost:1080'
}
```
or
```
module.exports = {
proxy: 'http://localhost:8123'
}
```
| Protocol    | Example
|:--------------:|:------------:
| `http`         | `http://www.example.com:port`
| `https`        | `https://www.example.com:port`
| `socks(v5)`| `socks://{username:password}@www.example.com:port`
| `socks5`    | `socks5://{username:password}@www.example.com:port`
| `socks4`    | `socks4://www.example.com:port`
| `pac`          | `pac+http://www.example.com/proxy.pac`
Only tested on Linux (Ubuntu 16.10).
> Add proxy agent (Support SOCKS and HTTP protocol)

- app/containers/settingPage/index.js
- package.json
In [160](https://github.com/hackjutsu/Lepton/issues/160), Evil icons's license (MIT) is required to be added. 
Please see the following:
Do we need order the licenses?
> Add license of Evil icons in ABOUT panel 

- package.json
Refer to https://github.com/hackjutsu/Lepton/issues/164
Test successfully after upgrading new node sass.
Test environment is Node 8.2.1. macOS Sierra. Node-sass 4.5.3.
The issue before was that node sass did not support node 8.
If any error like:
> Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x
Please rebuild node-sass like
> npm rebuild node-sass
> upgrade node sass

- package.json
Hi! I put together this PR to add a [snap](https://snapcraft.io) package. I've tested it on Ubuntu 16.04, 17.10, and 18.04, but it should work just as well on Ubuntu 14.04, Linux Mint, Manjaro, Debian, OpenSUSE, Solus, etc.
If you merge and `npm run dist` it will create `dist/lepton_1.5.1_amd64.snap`.
Copy this to a Linux system, [enable snap support](https://docs.snapcraft.io/core/install), then run:
`sudo snap install --dangerous lepton_1.5.1_amd64.snap`
Run with `lepton` or find it in the launcher.
If you create a developer account and push this to the Snap Store, it can be discovered and installed through GNOME Software and https://snapcraft.io/discover. To create the developer account, [sign up here](https://dashboard.snapcraft.io/dev/account/), then [register the "lepton" …
> Add a snap package (https://snapcraft.io) 

- app/containers/snippetPanel/index.scss
Closes #281
Adds snippet scrolling even when the window doesn't have focus. Retains hiding the scrollbars unless the snippet pane is hovered over.
> Enable snippet scrolling even when window doesn't have focus

- app/containers/codeArea/index.js
> #240 - fix multiline comment highlighting

- app/containers/codeArea/index.js
When copying text from `CodeArea`, empty lines would get lost. This PR fixes this by inserting a newline character into empty lines (instead of an empty string).
> fix: preserve newlines when copying from codeArea

- package-lock.json
- package.json
The issue caused by out-dated chrome will be healed by upgrading electron to latest stable version.
https://github.com/hackjutsu/Lepton/issues/340
I've tested and complied correctly in macOS Mojave 10.14.3
BTW, the chrome version in electron 4.0 is 69, while that in electron 3.0 is 68. Both are ok to avoid auth issue.
> upgrade electron to 4.0.5

- app/containers/navigationPanel/index.scss
- app/containers/navigationPanelDetails/index.scss
Another proposal to mitigate the issue https://github.com/hackjutsu/Lepton/issues/342 by shrinking the size of the scrollbar tracker. This doesn't solve the `overlay` issue, but will at least
1. consistent across scrollbars in different panels
2. make the blank verticle space less visible in the middle panel
> enhance: small tweaks on scrollbar style

- app/utilities/markdown/index.js
I have fixed the issue I reported here: https://github.com/hackjutsu/Lepton/issues/368
It was a somewhat tricky issue to debug because of the inconsistent rendering of markdown code blocks that were supposedly in the same language. The issue was that even if the language was explicitly declared at the top of a code block it would always run highlightAuto(). The functionality of highlightAuto is to guess the language based on the content, so even if python was explicitly declared highlightjs would make a guess based on the code, which was incorrect nearly every time. Highlight js would apply varying code styles to python code blocks like angelscript, matlab, moonscript, ruby, just to name a few. I fixed this issue by adding a conditional that checks if language is set, if set it will run …
> Fixed syntax highlighting in markdown.

- app/utilities/markdown/index.js
Automatically creates a link when a url is detected. Makes it much easier to add links to MDs. This mimics the behavior of gist.github.com.
> feature: automatically creates link when url is detected in md

- app/utilities/vendor/highlightJS/styles/github-gist.css
- package-lock.json
- package.json
Updated github-gist styles to match the current styling of gist.github.com. Also updated highlight.js package. See my commit to hightlight.js: https://github.com/highlightjs/highlight.js/commit/ea2a4cd4e4eb194f1d73ca4ed782fef37ff6f59d
> Bump highlight.js/update GitHub gist css

- app/utilities/menu/mainMenu.js
This PR is a workaround to the mismatch `Zoom In` menu item.
The issue related is the #390.
As a background context adition the issue #388 has some infos too.
The default combination for `ZoomIn` is `Shif+CmdOrCtrl+Plus`. 
This mismatch is caused by Electron and not Lepton.
Not the ideal solution, but I looked through Electron discussions and see many different points of discussion about this issue.
This is a workaround where we change the `Zoom In` shortcut to `CmdOrCtrl+=`.
> Change Zoom In Shortcut

- README.md
- app/containers/snippet/index.js
- app/index.js
- configs/defaultConfig.js
- main.js
@hackjutsu Adding Del key as shortcut comes in handy when you want to quickly cleanup your gists. The code on `app/index.js` could be refactored to remove duplication from older code, but I want to start easy for now. I will push some code refactoring later in another commit if you allow me to do this. I also have more improvements to commit. Hope this helps. ;)
When you have some time can you please take a look at this. Thanks!
> Added 'Delete' as a shortcut key for deleting the selected gist

- .gitignore
- README.md
- app/actions/index.js
- app/containers/snippet/index.js
- app/containers/userPanel/index.js
- app/index.js
- app/utilities/githubApi/index.js
- app/utilities/notifier/index.js
- configs/defaultConfig.js
I have most notifications on all my devices reduced to a minimum. To reduce notification fatigue,  I'm only interested in important notifications. For Lepton, I'm only interested in exceptional notifications, i.e. where the expected result hasn't occurred. I think it's especially important for macOS because these notifications cannot be force closed.
- No longer needed, can achieve similar behaviour with config for notification types, or can already block all app notifications at the OS level
- Wasn't documented anywhere except in #382, so may only affect a small number of users
> Configure notifications by type

- app/index.js
- main.js
Although Windows API support both forward slash and backslash. But in common sense, Windows should use forward slash as path separator, especially cmd and other command shells usually doesn't support backslash. So the most robust solution is follow the os specified path separator, we can use `path.join` to implement it.
The most important is that, Lepton has shown the config path in UI (About dialog). For now, it shown mixed path separators in one path, it makes user confused. So I fixed it.
Expected (after this fix):
Actual (before this fix):
> Fix: using path.join instead of concatenate path strings directly.

- README.md
Calling `brew cask install`is deprecated. We have to use `brew install --cask` instead.
> Update brew cask installation command

- app/containers/appContainer/scrollbar.scss
close #510 
the css that controls scrollbar to disappear, should exclude modal css.
> fix: modal scrollbar blink

- main.js
Adds support for XDG spec. See: https://wiki.archlinux.org/title/XDG_Base_Directory.
Basically, if `XDG_CONFIG_HOME` is defined as an environment variable, then the `.leptonrc` will be stored at `${XDG_CONFIG_HOME}/.leptonrc` instead.
This helps keep user home directories clean.
Closes #504
> Adds support for XDG spec
