hackjutsu/Lepton

package.json

add back `npm run pack` script

---

app/actions/index.js
app/containers/userPanel/index.js
app/reducers/index.js
app/reducers/reducer_logout_modal.js

Add a confirmation dialog when user clicks logout button, which shows "Cancel" and "Logout" buttons for cancel and confirm.

add logout confirmation dialog

---

app/containers/gistEditorForm/index.js
app/containers/gistEditorForm/index.scss
package.json

Adopt 3rd editor: CodeMirror

---

app/containers/gistEditorForm/index.js
app/containers/gistEditorForm/index.scss

Extend gutter to fill up CodeMirror editor

---

app/containers/snippet/index.js

One-click copy gist file content

---

app/containers/settingPage/index.js

fix issue #138 and thanks for sharing!

fix LICENSE link

---

README.md
app/containers/settingPage/index.js

add new contributors and installation section in README
Thanks again!
issue #144

add new contributors and installation section in README

---

app/containers/navigationPanel/index.scss

fix horizontal scrollbar issue #154

Horizontal scrollbar is now the same as vertical

---

app/containers/navigationPanel/index.scss

fix expanded tag section

---

app/containers/snippet/ic_collapsed.svg
app/containers/snippet/index.js
app/containers/snippet/index.scss

Fix white space around arrow icon

---

app/containers/navigationPanelDetails/index.scss

Fix snippet navigation scroll

---

app/containers/userPanel/index.scss

Progress bar takes the same width as the avatar

---

package.json

refer [165](https://github.com/hackjutsu/Lepton/issues/165) 
test on macOS Sierra, webpack 3.5.2

upgrade webpack

---

README.md
app/containers/settingPage/index.js

add cixuuz as a contributor in readme and settings

Add contributor

---

main.js
package-lock.json
package.json

Fixes #181 
Used [electron-is-dev](https://github.com/sindresorhus/electron-is-dev) library.

Run update checker only in non-development environment

---

app/containers/snippet/index.scss

I think these arrow direction are reverse #173

fix file-expand arrow direction

---

README.md
app/containers/aboutPage/index.js

I changed my GitHub username after joined Microsoft(LinkedIn). Just want to make sure the link here is still valid. Sorry for the inconvenience!

Updated my Github username

---

app/containers/userPanel/index.js
configs/defaultConfig.js

Makes profile photo display configurable. Default is `false` that means protect previous behaviour.

Optional profile photo

---

README.md
app/containers/aboutPage/index.js

add new contributor

---

app/utilities/notifier/index.js
configs/defaultConfig.js

Add a new property to `.leptonrc` file `disableNotification`, that defaults to `false`.
It will disable *all* notifications tho.

#377 Disable Notifications

---

configs/defaultConfig.js
main.js

Hey I really like the project! Great work!
From my point, configuring the shortcuts were missing - so here we go.
I have added the possibility to override the shortcuts in the main.js by setting them in .leptonrc file.
This would also work for partial overrides.
e.g. in your _< homeDir >/.leptonrc_
_partial_
```javascript
{
"theme": "dark",
...
"shortcuts": {
"keyNewGist": "CMD+C",
"keyDashboard": "CommandOrControl+D",
"keyEditorExit": "CommandOrControl+Escape",
"keySyncGists": "CommandOrControl+R"
}
}
```
_full_
```javascript
{
"theme": "dark",
...
"shortcuts": {
"keyShortcutForSearch": "CMD+F",
"keyNewGist": "CommandOrControl+N",
"keyEditGist": "CommandOrControl+E",
"keySubmitGist": "CommandOrControl+S",
"keyImmersiveMode": "CommandOrControl+I",
"keyAboutPage": "CommandOrControl+,", …
```

configure shortcuts via .leptonrc

---

README.md

$ git clone git@github.com:hackjutsu/Lepton.git wasn't working for me as it tried to login as 'git' user:
```
git clone git@github.com:hackjutsu/Lepton.git
Cloning into 'Lepton'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

Updated README.md developer instructions

---

app/index.js

Found a simple text misspelling on the comments.

Change "Acitive" for "Active"

---

app/utilities/githubApi/index.js

As soon as the pull request was created, the problem was fixed by @sunnysidesounds
fixed #489

Fix Deprecating API authentication through query parameters

---

main.js

add Minimize to disk
